# Change these first
owner: health-informatics-uon # Your GitHub organization or username, where this repository lives
repo: carrot-status # The name of this repository

sites:
  - name: Carrot Website
    url: https://carrot.ac.uk
  - name: Carrot Mapper
    url: https://mapper.carrot.ac.uk
  - name: Carrot API
    url: https://api.carrot.ac.uk/api/v2/scanreports/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.carrot.ac.uk
  # baseUrl: /carrot-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Carrot Status
  introTitle: "**Carrot Status** is the uptime monitor and status page for Carrot."
  introMessage: Our team are monitoring and alerted by the status of this page.
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - AndrewThien
  - AndyRae
